# Generated by Django 4.1 on 2022-10-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=126)),
                ("Last_Name", models.CharField(max_length=126)),
                ("Email", models.EmailField(max_length=266, unique=True)),
            ],
        ),
    ]
